### PR TITLE
Migrate to modern Android Studio project structure

### PR DESCRIPTION
**Pull request by z3ntu**

### CODE REVIEW

**Comment by Roboe** [comment]
Uh, I rebased your work on top of `master` and this issue automatically closed... Sorry.

**Comment by z3ntu** [comment]
I think I did a better job with the proguard rules in this PR. Now there's `app/proguard-rules.pro` which gets used with the `proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'` statement in the `app/build.gradle` file. The other proguard files are gone now.

**Comment by Roboe** [comment]
I agree and I like that ProGuard and project structure more, but I'm against renaming the java packages. We already changed the Android package name and the original code was written by Fairphone, just leave it in their folders. If we change these, then we need to change java packages for the other @WeAreFairphone/features-maintainers's packages too for coherence and I don't see any benefits, really.

**Comment by z3ntu** [comment]
The benefit in my eyes is that the package name aligns with how the project is structured. And as we have changed the "public" package name so why not change the internal one too?

The last commit (360cd56) fixes the weird Gradle error mentioned in #15

**Comment by Roboe** [comment]
Ok, no strong arguments for changing nor keeping the package name, so I'll accept yours.

**Comment by z3ntu** [comment]
Yeah... I haven't touched the launcher yet because it has some folders where I didn't immediately see what they were for. But I'll take a look at it again in the next days.

**Comment by Roboe** [comment]
Could you `rebase -i` this on top of the `master` branch now? I'd do this myself, but it will auto-close again... Note that for some reason there are two commits of myself that **should be here** (they are already in `master` but with different SHA)

I'll merge this once you do it, :+1:

**Comment by z3ntu** [comment]
Done (I've also squashed the last two commits into the first one)

**Comment by Roboe** [comment]
Upsie, I merged #9 before. Sorry for asking this again, @z3ntu.

**Comment by z3ntu** [comment]
Rebase didn't complain and `app/src/main/res/layout/clock_widget_main.xml` contains the changes from #9

**Comment by Roboe** [comment]
Git's smart, fortunately.

Good job, thank you! :)

**Pull request merged**
