### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Rudloff**

### CODE REVIEW

**Comment by z3ntu** [comment]
This widget neither includes Peace of Mind, nor "Your Fairphone for..."

**Comment by Rudloff** [comment]
I reused the description of the repository. If it is incorrect, it should be changed as well.

**Comment by z3ntu** [comment]
Told that Roboe yesterday, but he apparently didn't do it yet :slightly_smiling_face:

**Comment by Roboe** [comment]
Yeah, I put that in my backlog. See #4 too. I planned to fix the description and add repo `metadata` and `README.md` in the same go.

**Comment by Roboe** [comment]
Closing this because of #16

**Pull request closed without merging**
