### PR TITLE
React to 24-hour format preference change. Fix #10

### LINKED ISSUE #10: Widget doesn't react to change in "24-hour format" system preference
This is a regression (I guess) introduced by myself in a7eeefb28857d78b8f8c2230584cc543d46c0241

### PR DESCRIPTION
**Pull request by Roboe**
Fixes #10

### CODE REVIEW

**Comment by Roboe** [comment]
Please, @Rudloff, could you test this in your JB tablet? Specially if it is stuck on API 17

**Comment by Rudloff** [comment]
adb does not work on my tablet so I can't easily test this right now.

I tested on my Android 4.2.2 phone but it detects the preference change with or without this patch.

**Comment by Rudloff** [comment]
I tested on my Android 4.2.1 tablet and the widget also updates automatically with or without the patch.

**Comment by Roboe** [comment]
Thank you for reporting!

Well, the original code had a weird conditional in which, if the Android version were minor than `Build.VERSION_CODES.JELLY_BEAN_MR2`, it will check the 24-hour settings and update the time accordingly. The rest of versions just showed the time always in 24-hours format.

I didn't find any API incompatibilities in the methods used, so I asked you if you could check that precisely on JB just in case that was a case of mistaking `<` with `>`. Seems like the code just wasn't complete, so I'll merge this.

**Pull request merged**
